### ISSUE TITLE
Does the example for "defining a custom setter" require a reader

### ISSUE THREAD

**Issue by zoebisch** [learn-co-curriculum/forms-and-basic-associations-rails#19]
I ran into an issue with the following lab (Forms and Basic Associations Lab) where, only after adding a reader attribute would the writer method work.  I am not sure if this is missing from the example, but I don't see a difference otherwise?

**Comment by Ary770** [comment]
I have this same issue. Was a bit misleading for the lab. Hope they can update the lesson to be more complete and maybe explain why that reader method is needed....

**Comment by nikymorg** [comment]
Closed by commit bfdacca .
