### ISSUE TITLE
Code snippet 9 results in an error if you follow the tutorial exactly; New posts results in error if unchanged

### ISSUE THREAD

**Issue by Naomi-Dennis** [learn-co-curriculum/forms-and-basic-associations-rails#20]
Salutations! 

While following the Forms and Basic Association reading, I found a few errors in the code that's never addressed in the tutorial. 

## **Error 1: New posts results in error if unchanged**

If the code snippet from the tutorial here is left unchanged:

```  
 def category_name
      self.category.name
 end
```

And you follow the tutorial to the first category selection option: 

```  
<%= f.label :category_name %>
<%= f.text_field :category_name %>
<%= f.text_field :content %>
```

You will get the error: 

![image](https://user-images.githubusercontent.com/17726736/38948651-2519c8c2-430e-11e8-90c7-0ba5167ea8ef.png)

This happens because new post objects don't have categories and the category overloader doesn't check if a category is defined. New posts will find nothing and the error will crop up.  Because the tutorial is for creating a new post object, there's no way to avoid this without knowing it's there. There's probably a better way to fix this, but I just told it to return an empty string if no category is defined. That fixed the issue.

**My fix**

```
def category_name
   !self.category.nil? ? self.category.name  : ""
end

```

## **Error 2: The 9th code snippet results in an error if you follow the tutorial exactly**

When you get to this code snippet:

```
<%= form_for @post do |f| %>
  <%= f.collection_select :category, Category.all, :id, :name %>
  <%= f.text_field :content %>
<% end %>
```

You will get a nil error when the site is redirected to the post's show page after creating a new post or editing it since a category was never defined.

![image](https://user-images.githubusercontent.com/17726736/38948875-c433de52-430e-11e8-90ae-45392ab1aaa4.png)

This happens because the form submits a `:category object` instead of a `:category_name` object. 
Looking at the HTTP Request in the logs shows this: 

![image](https://user-images.githubusercontent.com/17726736/38948935-ef13d4ec-430e-11e8-8c32-ec4724f24198.png)

This happens because we changed the permit earlier to:

```
params.require(:post).permit(:category_name, :content)
```

It's doesn't find :category_name and just ignores :category so the category is never changed. 

**My Fix**

I fixed it by changing :category to :category_name. 
The final code looked like this: 
```
<%= form_for @post do |f| %>
  <%= f.collection_select :category_name, Category.all, :id, :name %>
  <%= f.text_field :content %>
<% end %>
```
Looking at the HTTP_Request, the data is correct:
![image](https://user-images.githubusercontent.com/17726736/38949047-411bd956-430f-11e8-9783-d0a6d9f40b68.png)

Personally, I changed it a bit more so the category name is passed to the ruby code instead of the id.
The change is the third parameter is now `:name` instead of `:id`. 
 
```
<%= form_for @post do |f| %>
  <%= f.collection_select :category_name, Category.all, :name, :name %>
  <%= f.text_field :content %>
<% end %>
```
![image](https://user-images.githubusercontent.com/17726736/38949119-78159dca-430f-11e8-8a33-64eb89abd5e4.png)

I created a git that contains the errors (it's commented out) with the fixed code. 

I used the displaying-associations-rails-v-000 lab code to test all of this and follow along with the reading; that's how I found the errors. I changed the :content to :description since that's the variable name in the project I'm using. 
---------------------------
I accidentally overwrote my lab :( 

Anyway, the fixes are shown here: 
https://github.com/Naomi-Dennis/displaying-associations-rails-v-000

**Comment by nikymorg** [comment]
Closed by #21. Thank you for submitting these issues!
