### ISSUE TITLE
Very confusing 

### ISSUE THREAD

**Issue by pipivybin** [learn-co-curriculum/forms-and-basic-associations-rails#23]
It introduces a lot of new concepts and knowledge points without explaining them clearly on what it is, why it is used or written in this way, when to use it or just whether it's important for us to understand it or just nice to know. I ended up having to ask the technical coaches, and google a lot of the new stuff showing up here. It's not an efficient or productive learning experience but rather pretty frustrating.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
