### ISSUE TITLE
The spec is looking for Genre Name in a Genre ID category 

### ISSUE THREAD

**Issue by polezo** [learn-co-curriculum/forms-and-basic-associations-rails#25]
The intent is to have a drop down with the genre name, but the spec appears to be looking for a Genre ID. Issue in song_form_spec

**Comment by sgharms** [comment]
This issue seems to be pointing to a different repo. I can't find a mention of songs or genres in this repo. Could you please re-open this issue on the repo that had this problem? Thanks!
